//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORY()
        {
            this.PRODUCTS = new HashSet<PRODUCT>();
        }
    
        public int CAT_ID { get; set; }
        public string CAT_NAME { get; set; }
        public string CAT_DESC { get; set; }
        public byte[] CAT_IMAGE { get; set; }
        public string CAT_STATUS { get; set; }
        public string CAT_CREATEDBY { get; set; }
        public string CAT_CREATEDDATE { get; set; }
        public string CAT_MODIBY { get; set; }
        public string CAT_MODIDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTS { get; set; }
    }
}
