//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int ORD_ID { get; set; }
        public int ORD_USERID { get; set; }
        public int ORD_PROID { get; set; }
        public int ORD_QTY { get; set; }
        public int ORD_TOTAL { get; set; }
        public string ORD_STATUS { get; set; }
        public string ORD_CREATEBY { get; set; }
        public string ORD_CREATEDATE { get; set; }
        public string ORD_MODIBY { get; set; }
        public string ORD_MODIDATE { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual USER USER { get; set; }
    }
}
